[package]
name = "diane"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.2.2"
bytes = "1.12.1"
chrono = "0.4.45"
clap = { version = "4.6.4", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6.0.0"
envy = "0.4.2"
ratatui = "0.30.2"
serde = {version = "1.0.229", features = ["derive"]}
tempfile = "3.27.0"
